import day8

def test_antinodes():
    inp = """..........
..........
..........
....a.....
..........
.....a....
..........
..........
..........
.........."""
    antenna_list = day8.get_antennas(inp)
    assert "a" in antenna_list

    antinodes = day8.get_antinodes(antenna_list)
    assert (6, 7) in antinodes
    assert (3, 1) in antinodes 

def test_part1():
    inp = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""
    assert 14 == day8.part1(inp)

def test_part_2_t_example():
    inp = """T.........
...T......
.T........
..........
..........
..........
..........
..........
..........
.........."""
    assert 9 == day8.part2(inp)

def test_part2():
    inp = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""
    assert 34 == day8.part2(inp)