import day6

input = """....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...
"""

def test_part1():
    assert day6.part1(input) == 41

def test_area_and_visit():
    assert day6.visit(day6.get_area(input), day6.Pos(4, 0)) == "#"

def test_part2():
    assert day6.part2(input) == 6